site_name: PentestDiaries
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    scheme: slate  # Dark mode
    primary: blue
    accent: cyan

nav:
  - Home: README.md
  - Penetration Testing:
      - Exploiting RD Gateway Vulnerability: ExploitingRDGatewayVuln.md
      - Exploiting SMTP Open Relays: Exploiting_SMTP_Open_Relays.md
      - How to Own a Bank: How_to_Own_a_Bank.md
  - Exploiting Vulnerabilities:
      - Ms Exchange Info Disclosure: MsExchangeInfoDisclosure.md
      - Shadow IT: shadowIT.md
      - SNMP GetBulk: snmpGetBulk.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

plugins:
  - search